"""add_household_consents

Revision ID: 63b6669a3360
Revises: 328e5419af52
Create Date: 2026-03-16 13:28:21.362544

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "63b6669a3360"
down_revision: Union[str, None] = "328e5419af52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "household_consents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("household_id", sa.Integer(), nullable=False),
        sa.Column("data_privacy_consent", sa.Boolean(), nullable=False),
        sa.Column("photo_media_release", sa.Boolean(), nullable=False),
        sa.Column("comm_email", sa.Boolean(), nullable=False),
        sa.Column("comm_sms", sa.Boolean(), nullable=False),
        sa.Column("comm_phone", sa.Boolean(), nullable=False),
        sa.Column("terms_acknowledged", sa.Boolean(), nullable=False),
        sa.Column(
            "consented_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.ForeignKeyConstraint(
            ["household_id"], ["households.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("household_consents")
    # ### end Alembic commands ###
