"""Add analytics tables

Revision ID: 7b6608946158
Revises: 2e885e89999b
Create Date: 2026-01-14 09:14:36.788773

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7b6608946158"
down_revision: Union[str, None] = "2e885e89999b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mass_attendance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("mass_time", sa.String(length=50), nullable=True),
        sa.Column("attendance_count", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mass_attendance_date"), "mass_attendance", ["date"], unique=False
    )
    op.create_table(
        "parish_statistics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "metric_type",
            sa.Enum(
                "BIRTH",
                "MASS_ATTENDANCE",
                "POPULATION",
                name="metric_type_enum",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("additional_data", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_parish_statistics_date"), "parish_statistics", ["date"], unique=False
    )
    op.create_index(
        op.f("ix_parish_statistics_metric_type"),
        "parish_statistics",
        ["metric_type"],
        unique=False,
    )
    op.create_table(
        "population_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("registered_members", sa.Integer(), nullable=False),
        sa.Column("households", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_population_snapshots_date"),
        "population_snapshots",
        ["date"],
        unique=True,
    )
    op.create_table(
        "births",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("baby_first_name", sa.String(length=100), nullable=False),
        sa.Column("baby_last_name", sa.String(length=100), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("parent1_id", sa.Integer(), nullable=True),
        sa.Column("parent2_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["parent1_id"], ["persons.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["parent2_id"], ["persons.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_births_baby_last_name"), "births", ["baby_last_name"], unique=False
    )
    op.create_index(
        op.f("ix_births_date_of_birth"), "births", ["date_of_birth"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_births_date_of_birth"), table_name="births")
    op.drop_index(op.f("ix_births_baby_last_name"), table_name="births")
    op.drop_table("births")
    op.drop_index(
        op.f("ix_population_snapshots_date"), table_name="population_snapshots"
    )
    op.drop_table("population_snapshots")
    op.drop_index(
        op.f("ix_parish_statistics_metric_type"), table_name="parish_statistics"
    )
    op.drop_index(op.f("ix_parish_statistics_date"), table_name="parish_statistics")
    op.drop_table("parish_statistics")
    op.drop_index(op.f("ix_mass_attendance_date"), table_name="mass_attendance")
    op.drop_table("mass_attendance")
    # ### end Alembic commands ###
