"""Add deaths table

Revision ID: a6260a847ea6
Revises: a726e468cbca
Create Date: 2026-02-02 13:44:51.829293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6260a847ea6'
down_revision: Union[str, None] = 'a726e468cbca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deaths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('date_of_death', sa.Date(), nullable=False),
    sa.Column('place_of_death', sa.String(length=255), nullable=True),
    sa.Column('cause_of_death', sa.String(length=255), nullable=True),
    sa.Column('burial_date', sa.Date(), nullable=True),
    sa.Column('burial_location', sa.String(length=255), nullable=True),
    sa.Column('funeral_date', sa.Date(), nullable=True),
    sa.Column('funeral_location', sa.String(length=255), nullable=True),
    sa.Column('officiating_priest_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['officiating_priest_id'], ['persons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deaths_date_of_death'), 'deaths', ['date_of_death'], unique=False)
    op.create_index(op.f('ix_deaths_person_id'), 'deaths', ['person_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deaths_person_id'), table_name='deaths')
    op.drop_index(op.f('ix_deaths_date_of_death'), table_name='deaths')
    op.drop_table('deaths')
    # ### end Alembic commands ###
