"""add unique constraint on family_relationships

Revision ID: c864d36f58b2
Revises: b4f7e2a91c03
Create Date: 2026-03-17 13:52:10.789255

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c864d36f58b2"
down_revision: Union[str, None] = "b4f7e2a91c03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Remove duplicate relationship records, keeping the one with the lowest id
    op.execute("""
        DELETE FROM family_relationships
        WHERE id NOT IN (
            SELECT MIN(id)
            FROM family_relationships
            GROUP BY person_id, related_person_id, relationship_type
        )
    """)
    op.create_unique_constraint(
        "uq_family_relationship",
        "family_relationships",
        ["person_id", "related_person_id", "relationship_type"],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_family_relationship", "family_relationships", type_="unique")
    # ### end Alembic commands ###
