"""add_notification_tables

Revision ID: d4ed2ffafc28
Revises: f3d78116a3fb
Create Date: 2026-05-04 19:59:10.311747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4ed2ffafc28'
down_revision: Union[str, None] = 'f3d78116a3fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reminder_type', sa.String(length=50), nullable=False),
    sa.Column('trigger_entity_type', sa.String(length=50), nullable=False),
    sa.Column('trigger_entity_id', sa.Integer(), nullable=False),
    sa.Column('hours_before', sa.Integer(), nullable=False),
    sa.Column('fired_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('recipients_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reminder_type', 'trigger_entity_type', 'trigger_entity_id', 'hours_before', 'fired_at', name='uq_reminder_dedup')
    )
    op.create_table('notification_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deliveries_created', 'notification_deliveries', ['created_at'], unique=False)
    op.create_index('ix_deliveries_person_read', 'notification_deliveries', ['person_id', 'read_at'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_person_id'), 'notification_deliveries', ['person_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'category', 'channel', name='uq_person_category_channel')
    )
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('ministry_id', sa.Integer(), nullable=True),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['persons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ministry_id'], ['ministries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('announcements')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_notification_deliveries_person_id'), table_name='notification_deliveries')
    op.drop_index('ix_deliveries_person_read', table_name='notification_deliveries')
    op.drop_index('ix_deliveries_created', table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_table('reminder_log')
    # ### end Alembic commands ###
