"""add_roster_tables

Revision ID: f3d78116a3fb
Revises: efe9f643b237
Create Date: 2026-05-04 17:18:49.231921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3d78116a3fb'
down_revision: Union[str, None] = 'efe9f643b237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roster_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['persons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('person_roster_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['persons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roster_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'role_id', name='uq_person_roster_role')
    )
    op.create_index(op.f('ix_person_roster_roles_person_id'), 'person_roster_roles', ['person_id'], unique=False)
    op.create_index(op.f('ix_person_roster_roles_role_id'), 'person_roster_roles', ['role_id'], unique=False)
    op.create_table('roster_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ministry_id', sa.Integer(), nullable=True),
    sa.Column('mass_time_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('recurrence_rule', sa.String(length=20), nullable=False),
    sa.Column('recurrence_end', sa.Date(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['persons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['ministry_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mass_time_id'], ['mass_times.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ministry_id'], ['ministries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roster_templates_ministry_id'), 'roster_templates', ['ministry_id'], unique=False)
    op.create_table('roster_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['roster_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roster_instances_date'), 'roster_instances', ['date'], unique=False)
    op.create_index(op.f('ix_roster_instances_template_id'), 'roster_instances', ['template_id'], unique=False)
    op.create_table('roster_template_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('min_persons', sa.Integer(), nullable=False),
    sa.Column('max_persons', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roster_roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['roster_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roster_template_slots_template_id'), 'roster_template_slots', ['template_id'], unique=False)
    op.create_table('roster_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('declined_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['persons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instance_id'], ['roster_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['roster_template_slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id', 'slot_id', 'person_id', name='uq_instance_slot_person')
    )
    op.create_index(op.f('ix_roster_assignments_instance_id'), 'roster_assignments', ['instance_id'], unique=False)
    op.create_index(op.f('ix_roster_assignments_person_id'), 'roster_assignments', ['person_id'], unique=False)
    op.create_index(op.f('ix_roster_assignments_slot_id'), 'roster_assignments', ['slot_id'], unique=False)
    op.create_table('roster_swap_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('from_person_id', sa.Integer(), nullable=False),
    sa.Column('to_person_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['roster_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roster_swap_requests_assignment_id'), 'roster_swap_requests', ['assignment_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roster_swap_requests_assignment_id'), table_name='roster_swap_requests')
    op.drop_table('roster_swap_requests')
    op.drop_index(op.f('ix_roster_assignments_slot_id'), table_name='roster_assignments')
    op.drop_index(op.f('ix_roster_assignments_person_id'), table_name='roster_assignments')
    op.drop_index(op.f('ix_roster_assignments_instance_id'), table_name='roster_assignments')
    op.drop_table('roster_assignments')
    op.drop_index(op.f('ix_roster_template_slots_template_id'), table_name='roster_template_slots')
    op.drop_table('roster_template_slots')
    op.drop_index(op.f('ix_roster_instances_template_id'), table_name='roster_instances')
    op.drop_index(op.f('ix_roster_instances_date'), table_name='roster_instances')
    op.drop_table('roster_instances')
    op.drop_index(op.f('ix_roster_templates_ministry_id'), table_name='roster_templates')
    op.drop_table('roster_templates')
    op.drop_index(op.f('ix_person_roster_roles_role_id'), table_name='person_roster_roles')
    op.drop_index(op.f('ix_person_roster_roles_person_id'), table_name='person_roster_roles')
    op.drop_table('person_roster_roles')
    op.drop_table('roster_roles')
    # ### end Alembic commands ###
